<?php

namespace Decoyeso\PedidoBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PresupuestoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PresupuestoRepository extends EntityRepository
{
}