parameters:
#    buscador.example.class: Coobix\BuscadorBundle\Example

services:
#    buscador.example:
#        class: %buscador.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
